name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -r placefinder/requirements.txt

    - name: Debug pytest installation
      run: |
        python -m pip show pytest
        which pytest || echo "pytest not in PATH"
        python -m pytest --version || echo "python -m pytest failed"

    - name: Run tests
      run: |
       PYTHONPATH=placefinder python -m pytest

    - name: Build Docker image
      run: |
        docker build -t placefinder-ci .
